AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  user-pool-demo

  Sample SAM Template for user-pool-demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DemoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      # AdminCreateUserConfig: AdminCreateUserConfig
      # AliasAttributes:
      #   - String
      AutoVerifiedAttributes:
        - email
      # DeviceConfiguration: DeviceConfiguration
      # EmailConfiguration: EmailConfiguration
      # EmailVerificationMessage: Please click the link below to verify your email address. {####}
      # EmailVerificationSubject: Your verification link
      # EnabledMfas:
      #   - SOFTWARE_TOKEN_MFA
      # LambdaConfig: LambdaConfig
      # MfaConfiguration: OPTIONAL
      # Policies: Policies
      Schema:
        - AttributeDataType: String
          Name: email
        - AttributeDataType: String
          Name: is_first_login
        - AttributeDataType: String
          Name: role
      # SmsAuthenticationMessage: String
      # SmsConfiguration: SmsConfiguration
      # SmsVerificationMessage: String
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: true
      # UserPoolAddOns: UserPoolAddOns
      UserPoolName: DemoPool
      # UserPoolTags: Json
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: Please click the link below to verify your email address. {##Verify Email##}
        EmailSubjectByLink: Your verification link

  DemoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      # AccessTokenValidity: Integer
      # AllowedOAuthFlows:
      #   - String
      # AllowedOAuthFlowsUserPoolClient: Boolean
      # AllowedOAuthScopes:
      #   - String
      # AnalyticsConfiguration: AnalyticsConfiguration
      # CallbackURLs:
      #   - String
      ClientName: DemoClient
      # DefaultRedirectURI: String
      # ExplicitAuthFlows:
      #   - String
      # GenerateSecret: Boolean
      # IdTokenValidity: Integer
      # LogoutURLs:
      #   - String
      PreventUserExistenceErrors: ENABLED
      ReadAttributes:
        - email
        - custom:role
        - custom:is_first_login
      # RefreshTokenValidity: Integer
      # SupportedIdentityProviders:
      #   - String
      # TokenValidityUnits: TokenValidityUnits
      UserPoolId: !Ref DemoUserPool
      WriteAttributes:
        - email
        - custom:role
        - custom:is_first_login
